import { MigrationInterface, QueryRunner } from "typeorm";

export class PhysiotherapistApiMigrations1686132848260 implements MigrationInterface {
    name = 'PhysiotherapistApiMigrations1686132848260'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "patient_pt" ("pt_id" SERIAL NOT NULL, "pt_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "pt_social_security_number" character varying NOT NULL, "pt_email_address" character varying NOT NULL, "pt_firstname" character varying NOT NULL, "pt_lastname" character varying NOT NULL, "pt_phone_number" character varying NOT NULL, "pt_street_line_address" character varying NOT NULL, "pt_city_address" character varying NOT NULL, "pt_zipcode_address" character varying NOT NULL, "pt_latitude_address" integer NOT NULL, "pt_longitude_address" integer NOT NULL, "pt_creation_date" TIMESTAMP NOT NULL DEFAULT now(), "pt_update_date" TIMESTAMP NOT NULL DEFAULT now(), "pt_deleted" TIMESTAMP, CONSTRAINT "UQ_c528f65f24f90e74c6806a2220a" UNIQUE ("pt_uuid"), CONSTRAINT "UQ_e6516e34d3dbcd6def9b1e8aa67" UNIQUE ("pt_social_security_number"), CONSTRAINT "UQ_24b31e8dcf1f7a65af229ef445d" UNIQUE ("pt_email_address"), CONSTRAINT "PK_945e8f86ba8ecdaf30ad3965a78" PRIMARY KEY ("pt_id"))`);
        await queryRunner.query(`CREATE TABLE "medicalprescription_mpn" ("mpn_id" SERIAL NOT NULL, "mpn_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "mpn_prescribing_doctore" character varying NOT NULL, "mpn_prescribing_date" TIMESTAMP NOT NULL, "mpn_total_expected_meetings" integer NOT NULL, "mpn_pathology" character varying NOT NULL, "mpn_commentary" character varying NOT NULL, "mpn_patient_uuid" uuid NOT NULL, "mpn_creation_date" TIMESTAMP NOT NULL DEFAULT now(), "mpn_update_date" TIMESTAMP NOT NULL DEFAULT now(), "mpn_deleted" TIMESTAMP, CONSTRAINT "UQ_fd25d517a6186a10e1e49cc5d70" UNIQUE ("mpn_uuid"), CONSTRAINT "PK_64c2325067874cf8a241e9b9956" PRIMARY KEY ("mpn_id"))`);
        await queryRunner.query(`CREATE TABLE "user_u" ("u_id" SERIAL NOT NULL, "u_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "u_email_address" character varying NOT NULL, "u_password" character varying NOT NULL, "u_creation_date" TIMESTAMP NOT NULL DEFAULT now(), "u_update_date" TIMESTAMP NOT NULL DEFAULT now(), "u_deleted" TIMESTAMP, CONSTRAINT "UQ_96185960c711ca4d3767b6a08b3" UNIQUE ("u_uuid"), CONSTRAINT "UQ_25e06e028ee0466333c381f2066" UNIQUE ("u_email_address"), CONSTRAINT "PK_1eae7d307fe10cb6d011a86025f" PRIMARY KEY ("u_id"))`);
        await queryRunner.query(`CREATE TABLE "practitioner_pr" ("pr_id" SERIAL NOT NULL, "pr_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "pr_social_security_number" character varying NOT NULL, "pr_email_address" character varying NOT NULL, "pr_firstname" character varying NOT NULL, "pr_lastname" character varying NOT NULL, "pr_phone_number" character varying NOT NULL, "pr_street_line_address" character varying NOT NULL, "pr_city_address" character varying NOT NULL, "pr_zipcode_address" character varying NOT NULL, "pr_latitude_address" integer NOT NULL, "pr_longitude_address" integer NOT NULL, "pr_speciality" character varying NOT NULL, "pr_user_uuid" uuid NOT NULL, "pr_creation_date" TIMESTAMP NOT NULL DEFAULT now(), "pr_update_date" TIMESTAMP NOT NULL DEFAULT now(), "pr_deleted" TIMESTAMP, CONSTRAINT "UQ_9ce743a8d9e58f3fcfe9a7993af" UNIQUE ("pr_uuid"), CONSTRAINT "UQ_4113c92a29f7471f1febf78ea50" UNIQUE ("pr_social_security_number"), CONSTRAINT "UQ_9ba459acd0b7e9c006587cf6c9f" UNIQUE ("pr_email_address"), CONSTRAINT "REL_1a7459345655b2665b84e0e205" UNIQUE ("pr_user_uuid"), CONSTRAINT "PK_80e668b3b0b373bb1ac39387d53" PRIMARY KEY ("pr_id"))`);
        await queryRunner.query(`CREATE TABLE "medicalprocedure_mpe" ("mpe_id" SERIAL NOT NULL, "mpe_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "mpe_title" character varying NOT NULL, "mpe_designation" character varying NOT NULL, "mpe_price" integer NOT NULL, "mpe_duration_in_minutes" integer NOT NULL, "mpe_practitioner_uuid" uuid NOT NULL, "mpe_creation_date" TIMESTAMP NOT NULL DEFAULT now(), "mpe_update_date" TIMESTAMP NOT NULL DEFAULT now(), "mpe_deleted" TIMESTAMP, CONSTRAINT "UQ_100be13b26effd63d2c5c91b37b" UNIQUE ("mpe_uuid"), CONSTRAINT "PK_6dde90fee7c952d118dc236d00b" PRIMARY KEY ("mpe_id"))`);
        await queryRunner.query(`CREATE TABLE "meeting_m" ("m_id" SERIAL NOT NULL, "m_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "m_status" character varying NOT NULL, "m_is_date_fixed" boolean NOT NULL, "m_charged_price" integer NOT NULL, "m_expected_start_date" TIMESTAMP NOT NULL, "m_start_date" TIMESTAMP NOT NULL, "m_expected_end_date" TIMESTAMP NOT NULL, "m_end_date" TIMESTAMP NOT NULL, "m_commentary" character varying NOT NULL, "m_patient_uuid" uuid NOT NULL, "m_practitioner_uuid" uuid NOT NULL, "m_medical_prescription_uuid" uuid NOT NULL, "m_medical_procedure_uuid" uuid NOT NULL, "m_creation_date" TIMESTAMP NOT NULL DEFAULT now(), "m_update_date" TIMESTAMP NOT NULL DEFAULT now(), "m_deleted" TIMESTAMP, CONSTRAINT "UQ_3927497373ea482922574f1612c" UNIQUE ("m_uuid"), CONSTRAINT "PK_465e4eac35f241f9a8ddcdbcf9e" PRIMARY KEY ("m_id"))`);
        await queryRunner.query(`ALTER TABLE "medicalprescription_mpn" ADD CONSTRAINT "FK_8dace1d9adfc58acab08657e9f0" FOREIGN KEY ("mpn_patient_uuid") REFERENCES "patient_pt"("pt_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practitioner_pr" ADD CONSTRAINT "FK_1a7459345655b2665b84e0e2059" FOREIGN KEY ("pr_user_uuid") REFERENCES "user_u"("u_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medicalprocedure_mpe" ADD CONSTRAINT "FK_050290666bc7d791b05079aec15" FOREIGN KEY ("mpe_practitioner_uuid") REFERENCES "practitioner_pr"("pr_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_m" ADD CONSTRAINT "FK_412f511d75008e1e472a7779cf2" FOREIGN KEY ("m_patient_uuid") REFERENCES "patient_pt"("pt_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_m" ADD CONSTRAINT "FK_28683c336d12bdf4765fe515a8e" FOREIGN KEY ("m_practitioner_uuid") REFERENCES "practitioner_pr"("pr_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_m" ADD CONSTRAINT "FK_58ab3b67580e747b66076cdc938" FOREIGN KEY ("m_medical_prescription_uuid") REFERENCES "medicalprescription_mpn"("mpn_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_m" ADD CONSTRAINT "FK_e31d7af7e72b03bfc18ca134a4b" FOREIGN KEY ("m_medical_procedure_uuid") REFERENCES "medicalprocedure_mpe"("mpe_uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "meeting_m" DROP CONSTRAINT "FK_e31d7af7e72b03bfc18ca134a4b"`);
        await queryRunner.query(`ALTER TABLE "meeting_m" DROP CONSTRAINT "FK_58ab3b67580e747b66076cdc938"`);
        await queryRunner.query(`ALTER TABLE "meeting_m" DROP CONSTRAINT "FK_28683c336d12bdf4765fe515a8e"`);
        await queryRunner.query(`ALTER TABLE "meeting_m" DROP CONSTRAINT "FK_412f511d75008e1e472a7779cf2"`);
        await queryRunner.query(`ALTER TABLE "medicalprocedure_mpe" DROP CONSTRAINT "FK_050290666bc7d791b05079aec15"`);
        await queryRunner.query(`ALTER TABLE "practitioner_pr" DROP CONSTRAINT "FK_1a7459345655b2665b84e0e2059"`);
        await queryRunner.query(`ALTER TABLE "medicalprescription_mpn" DROP CONSTRAINT "FK_8dace1d9adfc58acab08657e9f0"`);
        await queryRunner.query(`DROP TABLE "meeting_m"`);
        await queryRunner.query(`DROP TABLE "medicalprocedure_mpe"`);
        await queryRunner.query(`DROP TABLE "practitioner_pr"`);
        await queryRunner.query(`DROP TABLE "user_u"`);
        await queryRunner.query(`DROP TABLE "medicalprescription_mpn"`);
        await queryRunner.query(`DROP TABLE "patient_pt"`);
    }

}
